pipeline{
    
    agent any
    
    tools {
	maven "Maven 3.6.1"

    }

    stages {
        stage(build){
            steps{
                echo "Building worker app"
				dir('worker'){
		  			sh 'mvn compile'
		  			sleep 3
                }
            }	
        }
        stage(test){
            steps{
                echo "Testing worker app"
				dir('worker'){
		  			sh 'mvn test'
                  	sleep 3
				}            
        	}		
        }
        
        stage(package){
            steps{
                echo "Pacakaging worker app"
                dir('worker'){
		   			sh 'mvn package'
		   			sleep 3
                }  	
            }
        }
    }
    
    post{
        always{
            archiveArtifacts '**/target/*.jar'
	    	echo "Execution of all stages Done and packaging completed"
	    	sleep 3
        }
    }
}
