pipeline{
    
    agent any
    
    tools {
	maven "Maven 3.6.1"

    }

    stages {
        stage(build){
            steps{
                echo "Building worker app"
		dir('worker'){
		  sh 'mvn complie'
                  sleep 5
                }
            }	
        }
        stage(test){
            steps{
                echo "Hello Shiv to stage Two"
                sleep 5
            }
        }
        
        stage(package){
            steps{
                echo "Hello Shiv to stage Three"
                sleep 5
            }
        }
    }
    
    post{
        always{
            echo "Execution of all stages Done"
            sleep 10
        }
    }
}
